apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-dep
  template:
    metadata:
      labels:
        app: springboot-dep
    spec:
      containers:
      - name: springboot-container
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
